### ISSUE TITLE
Incorrect solution obtained via web interface

### ISSUE THREAD

**Issue by fangyi-zhou** [wgoodall01/shikaku#1]
For input

<img width="347" alt="input1" src="https://user-images.githubusercontent.com/7815439/47266460-d8f5cf00-d52e-11e8-82ee-8e062b58d0a5.png">

An incorrect solution is obtained
<img width="361" alt="output" src="https://user-images.githubusercontent.com/7815439/47266458-d8f5cf00-d52e-11e8-9fe7-dff9f64d7dea.png">

via web interface

**Comment by fangyi-zhou** [comment]
Or maybe rendering issue?

**Comment by wgoodall01** [comment]
https://github.com/wgoodall01/shikaku/blob/f57b18def8dc31e110669ea40695fb6d426706bd/board.go#L216-L225

The issue was in this block, on line 221--the solver assumed squares with 1 possible solution were already solved. They weren't.

Thanks for the error report :)

**Comment by fangyi-zhou** [comment]
Thanks for the fix!
